### ISSUE TITLE
searchex info - no function clause matching in Access.fetch

### ISSUE THREAD

**Issue by sstine** [elixir-search/searchex#7]
After installing searchex with `mix escript.install hex searchex` and downloading the sample repo with `searchex fetch elixir-search/sample`, running `searchex info` results in an error:

```
** (FunctionClauseError) no function clause matching in Access.fetch/2
    (elixir) lib/access.ex:239: Access.fetch({:error, "No file_roots"}, :cfg_name)
    (elixir) lib/access.ex:269: Access.get/3
    (elixir) lib/enum.ex:2195: anonymous fn/2 in Enum.sort_by/3
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (elixir) lib/enum.ex:2195: Enum.sort_by/3
    (searchex) lib/searchex/render/info.ex:26: Searchex.Render.Info.table_data/2
    (searchex) lib/searchex/render/info.ex:10: Searchex.Render.Info.to_table/1
    (searchex) lib/searchex/cli.ex:12: Searchex.Cli.main/1
```

`searchex ls` works fine:

```
$ searchex ls
constitution
genesis
tiny
```

However, searching doesn't appear to be working either:
```
➜  ~ searchex query genesis 'cain abel'
No file_roots
```

OS: MacOS Sierra 10.12.2
Elixir: 1.4.0

**Comment by cro** [comment]
I am seeing the same issue.  Furthermore I don't seem to be able to create my own indices:

```searchex build mydocrepo```

also generates

```No file_roots```

though my config file looks very similar to the ones in the samples.

OS: MacOS Sierra 10.12.3
Elixir: 1.4.1

**Comment by haslinger** [comment]
Same error here,
OS: Ubuntu 16.04
Elixir: 1.4.1
Searchex: 0.0.4
